### ISSUE TITLE
Error when running runner.py

### ISSUE THREAD

**Issue by cdoffx** [ozgen/cyriptopia-pump-and-dump#1]
i get this error when i tried to run bot like this python Runner.py --symbol XVGBTC
Traceback (most recent call last):
  File "Runner.py", line 9, in <module>
    CyriptopiaPumpAndDump.PumpDumpCyriptopia().pumpDump(str(coin_name.symbol).up
per())
  File "C:\Users\USER\Desktop\pumpbot\CyriptopiaPumpAndDump.py", line 28, in pum
pDump
    ASK_PRICE = COIN_PRICE['AskPrice']
TypeError: 'NoneType' object has no attribute '__getitem__'

what do i do

**Comment by ozgen** [comment]
the balance of XVG in your account is 0, so the error is occurred.
